name: Build

on:
  push:
    branches-ignore:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test Spring Application
      run: ./gradlew build
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}

    - name: Display API Information
      run: |
        echo "API Key is: $API_KEY"
        echo "API Base URL is: $API_BASE_URL"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
