name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Spring Application
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            sudo docker stop my-spring-container || true
            sudo docker rm my-spring-container || true
            sudo docker run -d --name my-spring-container -p 8080:8080 \
              -e SPRING_JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e API_BASE_URL=${{ secrets.API_BASE_URL }} \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e NAVER_API_URL=${{ secrets.NAVER_API_URL }} \
              -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
              -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest